---
title: "Mobile Sensors"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(png)
library(rgdal)
library(cartography)
library(ggpubr)
```


```{r}
##reading in sensor data
# Mobile_sensor <- read.csv("C:/Users/sbapt/Desktop/Smith/DATA CHALLENGES/#5/DC5-Data/Sensor Data and Maps/MobileSensorReadings.csv")

Mobile_sensor <- read.csv("MobileSensorReadings.csv")

##Reading in Image for background
img <- readPNG("map.png")

##Graph Theme
theme1 <- theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "grey"), panel.background = element_rect(fill = "white", colour = "white"))

```

##Tidying

```{r}
Mobile_sensor_06 <- Mobile_sensor %>%
  filter(grepl('04-06', Timestamp))

Mobile_sensor_07 <- Mobile_sensor %>%
  filter(grepl('04-07', Timestamp))

Mobile_sensor_08 <- Mobile_sensor %>%
  filter(grepl('04-08', Timestamp))

Mobile_sensor_09 <- Mobile_sensor %>%
  filter(grepl('04-09', Timestamp))

Mobile_sensor_10 <- Mobile_sensor %>%
  filter(grepl('04-10', Timestamp))

```

```{r}
# ggplot(Mobile_sensor_06, aes(x = Long, y = Lat)) +
#   background_image(img2) +
#   geom_point(alpha = 0.1, aes(color = Value)) +
#   theme_minimal() +
#   labs(x="Long", y = "Lat", title = "Coords") +
#   scale_x_continuous(limits = c(-120,-119.711751), expand = c(0, 0)) +
#   scale_y_continuous(limits = c(0, 0.237585), expand = c(0, 0)) +
#   scale_colour_gradient2(
#     low = "blue",
#     mid = "purple4",
#     high = "red",
#     midpoint = 27.5,
#     space = "Lab",
#     na.value = "grey50",
#     guide = "colourbar",
#     aesthetics = "color"
#   )
  
```

```{r}

# ##lat round
# Mobile_sensor_06 <- Mobile_sensor_06 %>%
#   #mutate(Long_round = format(round(Long, 3), nsmall = 3)) %>%
#   mutate(Lat_round = format(round(Lat, 4), nsmall = 4))
# 
# ##As int
# #Mobile_sensor_06$Long_round <- as.numeric(Mobile_sensor_06$Long_round)
# Mobile_sensor_06$Lat_round <- as.numeric(Mobile_sensor_06$Lat_round)
# 
# ##sectioning off all readings over 100
# Mobile_sensor_06_top <- Mobile_sensor_06 %>%
#   filter(Value >= 100)
# 
# ##sectioning off all readings under 100
# Mobile_sensor_06_low <- Mobile_sensor_06 %>%
#   filter(Value < 100)
# 
# 
# ##group long & Avg - SKIP
# # Mobile_sensor_06_low <- Mobile_sensor_06_low %>%
# #   group_by(Long_round) %>%
# #   mutate(Value_avg = mean(Value)) %>%
# #   ungroup()
# 
# ##group lat & Avg
# Mobile_sensor_06_low <- Mobile_sensor_06_low %>%
#   group_by(Lat_round) %>%
#   mutate(Value_avg_2 = mean(Value)) %>%
#   ungroup()
# 
# ##Average Value_avg and Value_avg_2
# # Mobile_sensor_06_low <- Mobile_sensor_06_low %>%
# #   mutate(Value_avg = ((Value_avg + Value_avg_2)/2))
# 
# ##Removing repeat values
# Mobile_sensor_06_sm <- Mobile_sensor_06_low %>%
#   select(Timestamp, Long, Lat_round, Value_avg_2)%>%
#   filter(duplicated(Lat_round) == FALSE)
# 
# # ggplot(Mobile_sensor_06_sm, aes(x = Lat_round, y = Long)) +
# #   geom_jitter(width = 0.01, height = 0.01, alpha = 0.7, aes(color = Value_avg_2)) +
# #   theme_minimal() +
# #   labs(x="Lat", y = "Long", title = "Coords")
# # 
# # ##adding the high end back onto the data
# # Mobile_sensor_06_top <- Mobile_sensor_06_top %>%
# #   select(Timestamp, Long, Lat_round, Value) %>%
# #   rename(Value_avg_2 = "Value")
# # 
# # Mobile_sensor_06_final <- Mobile_sensor_06_top %>%
# #   full_join(Mobile_sensor_06_sm)
# 
# # ##excluding high outliers
# # ggplot(Mobile_sensor_06_sm, aes(x = Long, y = Lat_round)) +
# #   geom_jitter(width = 0.01, height = 0.01, alpha = 0.7, aes(color = Value_avg_2)) +
# #   theme_minimal() +
# #   labs(x="Lat", y = "Long", title = "Coords") +
# #   scale_colour_gradient2(
# #     low = "blue",
# #     mid = "purple4",
# #     high = "red",
# #     midpoint = 27.5,
# #     space = "Lab",
# #     na.value = "grey50",
# #     guide = "colourbar",
# #     aesthetics = "color"
# #   )
# 
# ##High outliers graphed on top
# ggplot(NULL, aes(x = Long, y = Lat_round)) +
#   background_image(img) +
#   geom_jitter(data = Mobile_sensor_06_sm, width = 0.01, height = 0.01, alpha = 0.7, aes(color = Value_avg_2)) +
#   theme1 +
#   labs(x="Long", y = "Lat", title = "Mobile Sensor Radiation Readings on April, 06", color = "Avg. cpm") +
#   scale_colour_gradient2(
#     low = "blue",
#     mid = "purple4",
#     high = "red",
#     midpoint = 27.5,
#     space = "Lab",
#     na.value = "grey50",
#     guide = "colourbar",
#     aesthetics = "color"
#   ) +
#   geom_point(data = Mobile_sensor_06_top, col = "magenta") +
#   scale_x_continuous(limits = c(-120,-119.711751), expand = c(0, 0)) +
#   scale_y_continuous(limits = c(0, 0.237585), expand = c(0, 0))
```


```{r}
##Rounding the latitude & Longitude measurements to reduce the number of points (Grouping points that are essentially on top of each other anyways)
Mobile_sensor_06 <- Mobile_sensor_06 %>%
  mutate(Long_round = format(round(Long, 3), nsmall = 3)) %>%
  mutate(Lat_round = format(round(Lat, 3), nsmall = 3))

##As int
Mobile_sensor_06$Long_round <- as.numeric(Mobile_sensor_06$Long_round)
Mobile_sensor_06$Lat_round <- as.numeric(Mobile_sensor_06$Lat_round)

##sectioning off all readings over 100
Mobile_sensor_06_top <- Mobile_sensor_06 %>%
  filter(Value >= 100)

##sectioning off all readings under 100
Mobile_sensor_06_low <- Mobile_sensor_06 %>%
  filter(Value < 100)

##Averaging all points within the same longitudinal location
Mobile_sensor_06_low <- Mobile_sensor_06_low %>%
  group_by(Long_round) %>%
  mutate(Value_avg = mean(Value)) %>%
  ungroup()

##Averaging all points within the same lateral location
Mobile_sensor_06_low <- Mobile_sensor_06_low %>%
  group_by(Lat_round) %>%
  mutate(Value_avg_2 = mean(Value)) %>%
  ungroup()

##Average Value_avg and Value_avg_2 if both lat_round and long_round are unchanging over the range
Mobile_sensor_06_low <- Mobile_sensor_06_low %>%  
  group_by(Lat_round, Long_round) %>%
  mutate(Value_sum = sum(Value), Value_avg_f =(mean(Value))) %>%
  ungroup()

##Removing repeat values
Mobile_sensor_06_sm <- Mobile_sensor_06_low %>%
  select(Timestamp, Long_round, Lat_round, Value_avg_f)

Mobile_sensor_06_sm <- Mobile_sensor_06_sm[!duplicated(Mobile_sensor_06_sm[c("Lat_round","Long_round")]),]

##Graphing the low end avaeraged points with the above 100 outliers on top
ggplot(NULL, aes(x = Long_round, y = Lat_round)) +
  background_image(img) +
  geom_jitter(data = Mobile_sensor_06_sm, width = 0.01, height = 0.01, alpha = 0.7, aes(color = Value_avg_f)) +
  theme1 +
  labs(x="Long", y = "Lat", title = "Mobile Sensor Radiation Readings on April, 06", color = "Avg. cpm") +
  scale_colour_gradient2(
    low = "blue",
    mid = "purple4",
    high = "red",
    midpoint = 27.5,
    space = "Lab",
    na.value = "grey50",
    guide = "colourbar",
    aesthetics = "color"
  ) +
  geom_point(data = Mobile_sensor_06_top, col = "yellow2") +
  scale_x_continuous(limits = c(-120,-119.711751), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0, 0.237585), expand = c(0, 0))
```


```{r}
##Rounding the latitude & Longitude measurements to reduce the number of points (Grouping points that are essentially on top of each other anyways)
Mobile_sensor_07 <- Mobile_sensor_07 %>%
  mutate(Long_round = format(round(Long, 3), nsmall = 3)) %>%
  mutate(Lat_round = format(round(Lat, 3), nsmall = 3))

##As int
Mobile_sensor_07$Long_round <- as.numeric(Mobile_sensor_07$Long_round)
Mobile_sensor_07$Lat_round <- as.numeric(Mobile_sensor_07$Lat_round)

##sectioning off all readings over 100
Mobile_sensor_07_top <- Mobile_sensor_07 %>%
  filter(Value >= 100)

##sectioning off all readings under 100
Mobile_sensor_07_low <- Mobile_sensor_07 %>%
  filter(Value < 100)

##Averaging all points within the same longitudinal location
Mobile_sensor_07_low <- Mobile_sensor_07_low %>%
  group_by(Long_round) %>%
  mutate(Value_avg = mean(Value)) %>%
  ungroup()

##Averaging all points within the same lateral location
Mobile_sensor_07_low <- Mobile_sensor_07_low %>%
  group_by(Lat_round) %>%
  mutate(Value_avg_2 = mean(Value)) %>%
  ungroup()

##Average Value_avg and Value_avg_2 if both lat_round and long_round are unchanging over the range
Mobile_sensor_07_low <- Mobile_sensor_07_low %>%  
  group_by(Lat_round, Long_round) %>%
  mutate(Value_sum = sum(Value), Value_avg_f =(mean(Value))) %>%
  ungroup()

##Removing repeat values
Mobile_sensor_07_sm <- Mobile_sensor_07_low %>%
  select(Timestamp, Long_round, Lat_round, Value_avg_f)

Mobile_sensor_07_sm <- Mobile_sensor_07_sm[!duplicated(Mobile_sensor_07_sm[c("Lat_round","Long_round")]),]

##Graphing the low end avaeraged points with the above 100 outliers on top
ggplot(NULL, aes(x = Long_round, y = Lat_round)) +
  background_image(img) +
  geom_jitter(data = Mobile_sensor_07_sm, width = 0.01, height = 0.01, alpha = 0.7, aes(color = Value_avg_f)) +
  theme1 +
  labs(x="Long", y = "Lat", title = "Mobile Sensor Radiation Readings on April, 07", color = "Avg. cpm") +
  scale_colour_gradient2(
    low = "blue",
    mid = "purple4",
    high = "red",
    midpoint = 27.5,
    space = "Lab",
    na.value = "grey50",
    guide = "colourbar",
    aesthetics = "color"
  ) +
  geom_point(data = Mobile_sensor_07_top, col = "yellow2") +
  scale_x_continuous(limits = c(-120,-119.711751), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0, 0.237585), expand = c(0, 0))
```

```{r}
##Rounding the latitude & Longitude measurements to reduce the number of points (Grouping points that are essentially on top of each other anyways)
Mobile_sensor_08 <- Mobile_sensor_08 %>%
  mutate(Long_round = format(round(Long, 3), nsmall = 3)) %>%
  mutate(Lat_round = format(round(Lat, 3), nsmall = 3))

##As int
Mobile_sensor_08$Long_round <- as.numeric(Mobile_sensor_08$Long_round)
Mobile_sensor_08$Lat_round <- as.numeric(Mobile_sensor_08$Lat_round)

##sectioning off all readings over 100
Mobile_sensor_08_top <- Mobile_sensor_08 %>%
  filter(Value >= 100)

##sectioning off all readings under 100
Mobile_sensor_08_low <- Mobile_sensor_08 %>%
  filter(Value < 100)

##Averaging all points within the same longitudinal location
Mobile_sensor_08_low <- Mobile_sensor_08_low %>%
  group_by(Long_round) %>%
  mutate(Value_avg = mean(Value)) %>%
  ungroup()

##Averaging all points within the same lateral location
Mobile_sensor_08_low <- Mobile_sensor_08_low %>%
  group_by(Lat_round) %>%
  mutate(Value_avg_2 = mean(Value)) %>%
  ungroup()

##Average Value_avg and Value_avg_2 if both lat_round and long_round are unchanging over the range
Mobile_sensor_08_low <- Mobile_sensor_08_low %>%  
  group_by(Lat_round, Long_round) %>%
  mutate(Value_sum = sum(Value), Value_avg_f =(mean(Value))) %>%
  ungroup()

##Removing repeat values
Mobile_sensor_08_sm <- Mobile_sensor_08_low %>%
  select(Timestamp, Long_round, Lat_round, Value_avg_f)

Mobile_sensor_08_sm <- Mobile_sensor_08_sm[!duplicated(Mobile_sensor_08_sm[c("Lat_round","Long_round")]),]

##Graphing the low end avaeraged points with the above 100 outliers on top
ggplot(NULL, aes(x = Long_round, y = Lat_round)) +
  background_image(img) +
  geom_jitter(data = Mobile_sensor_08_sm, width = 0.01, height = 0.01, alpha = 0.7, aes(color = Value_avg_f)) +
  theme1 +
  labs(x="Long", y = "Lat", title = "Mobile Sensor Radiation Readings on April, 08", color = "Avg. cpm") +
  scale_colour_gradient2(
    low = "blue",
    mid = "purple4",
    high = "red",
    midpoint = 27.5,
    space = "Lab",
    na.value = "grey50",
    guide = "colourbar",
    aesthetics = "color"
  ) +
  geom_point(data = Mobile_sensor_08_top, col = "yellow2") +
  scale_x_continuous(limits = c(-120,-119.711751), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0, 0.237585), expand = c(0, 0))
```


```{r}
##Rounding the latitude & Longitude measurements to reduce the number of points (Grouping points that are essentially on top of each other anyways)
Mobile_sensor_09 <- Mobile_sensor_09 %>%
  mutate(Long_round = format(round(Long, 3), nsmall = 3)) %>%
  mutate(Lat_round = format(round(Lat, 3), nsmall = 3))

##As int
Mobile_sensor_09$Long_round <- as.numeric(Mobile_sensor_09$Long_round)
Mobile_sensor_09$Lat_round <- as.numeric(Mobile_sensor_09$Lat_round)

##sectioning off all readings over 100
Mobile_sensor_09_top <- Mobile_sensor_09 %>%
  filter(Value >= 100)

##sectioning off all readings under 100
Mobile_sensor_09_low <- Mobile_sensor_09 %>%
  filter(Value < 100)

##Averaging all points within the same longitudinal location
Mobile_sensor_09_low <- Mobile_sensor_09_low %>%
  group_by(Long_round) %>%
  mutate(Value_avg = mean(Value)) %>%
  ungroup()

##Averaging all points within the same lateral location
Mobile_sensor_09_low <- Mobile_sensor_09_low %>%
  group_by(Lat_round) %>%
  mutate(Value_avg_2 = mean(Value)) %>%
  ungroup()

##Average Value_avg and Value_avg_2 if both lat_round and long_round are unchanging over the range
Mobile_sensor_09_low <- Mobile_sensor_09_low %>%  
  group_by(Lat_round, Long_round) %>%
  mutate(Value_sum = sum(Value), Value_avg_f =(mean(Value))) %>%
  ungroup()

##Removing repeat values
Mobile_sensor_09_sm <- Mobile_sensor_09_low %>%
  select(Timestamp, Long_round, Lat_round, Value_avg_f)

Mobile_sensor_09_sm <- Mobile_sensor_09_sm[!duplicated(Mobile_sensor_09_sm[c("Lat_round","Long_round")]),]

##Graphing the low end avaeraged points with the above 100 outliers on top
ggplot(NULL, aes(x = Long_round, y = Lat_round)) +
  background_image(img) +
  geom_jitter(data = Mobile_sensor_09_sm, width = 0.01, height = 0.01, alpha = 0.7, aes(color = Value_avg_f)) +
  theme1 +
  labs(x="Long", y = "Lat", title = "Mobile Sensor Radiation Readings on April, 09", color = "Avg. cpm") +
  scale_colour_gradient2(
    low = "blue",
    mid = "purple4",
    high = "red",
    midpoint = 27.5,
    space = "Lab",
    na.value = "grey50",
    guide = "colourbar",
    aesthetics = "color"
  ) +
  geom_point(data = Mobile_sensor_09_top, col = "yellow2") +
  scale_x_continuous(limits = c(-120,-119.711751), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0, 0.237585), expand = c(0, 0))
```


```{r}
##Rounding the latitude & Longitude measurements to reduce the number of points (Grouping points that are essentially on top of each other anyways)
Mobile_sensor_10 <- Mobile_sensor_10 %>%
  mutate(Long_round = format(round(Long, 3), nsmall = 3)) %>%
  mutate(Lat_round = format(round(Lat, 3), nsmall = 3))

##As int
Mobile_sensor_10$Long_round <- as.numeric(Mobile_sensor_10$Long_round)
Mobile_sensor_10$Lat_round <- as.numeric(Mobile_sensor_10$Lat_round)

##sectioning off all readings over 100
Mobile_sensor_10_top <- Mobile_sensor_10 %>%
  filter(Value >= 100)

##sectioning off all readings under 100
Mobile_sensor_10_low <- Mobile_sensor_10 %>%
  filter(Value < 100)

##Averaging all points within the same longitudinal location
Mobile_sensor_10_low <- Mobile_sensor_10_low %>%
  group_by(Long_round) %>%
  mutate(Value_avg = mean(Value)) %>%
  ungroup()

##Averaging all points within the same lateral location
Mobile_sensor_10_low <- Mobile_sensor_10_low %>%
  group_by(Lat_round) %>%
  mutate(Value_avg_2 = mean(Value)) %>%
  ungroup()

##Average Value_avg and Value_avg_2 if both lat_round and long_round are unchanging over the range
Mobile_sensor_10_low <- Mobile_sensor_10_low %>%  
  group_by(Lat_round, Long_round) %>%
  mutate(Value_sum = sum(Value), Value_avg_f =(mean(Value))) %>%
  ungroup()

##Removing repeat values
Mobile_sensor_10_sm <- Mobile_sensor_10_low %>%
  select(Timestamp, Long_round, Lat_round, Value_avg_f)

Mobile_sensor_10_sm <- Mobile_sensor_10_sm[!duplicated(Mobile_sensor_10_sm[c("Lat_round","Long_round")]),]

##Graphing the low end avaeraged points with the above 100 outliers on top
ggplot(NULL, aes(x = Long_round, y = Lat_round)) +
  background_image(img) +
  geom_jitter(data = Mobile_sensor_10_sm, width = 0.01, height = 0.01, alpha = 0.7, aes(color = Value_avg_f)) +
  theme1 +
  labs(x="Long", y = "Lat", title = "Mobile Sensor Radiation Readings on April, 10", color = "Avg. cpm") +
  scale_colour_gradient2(
    low = "blue",
    mid = "purple4",
    high = "red",
    midpoint = 27.5,
    space = "Lab",
    na.value = "grey50",
    guide = "colourbar",
    aesthetics = "color"
  ) +
  geom_point(data = Mobile_sensor_10_top, col = "yellow2") +
  scale_x_continuous(limits = c(-120,-119.711751), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0, 0.237585), expand = c(0, 0))
```


```{r}

# # Read SHAPEFILE.shp from the current working directory (".")
# 
# require(rgdal)
# shape <- readOGR(dsn = "C:/Users/sbapt/Desktop/Smith/DATA CHALLENGES/#5/DC5-Data/Sensor Data and Maps/StHimarkNeighborhoodShapefiles", layer = "StHimark")
# 
# # Use the cartography library to do the choropleth map
# choroLayer(spdf = shape, df = shape@data, var = "Id")
# title("neighborhood")

```
